name: PlaybookExample
projectReferences:
  Playbook:
    path: ../Playbook.xcodeproj

options:
  bundleIdPrefix: app.playbook-ui.Example
  deploymentTarget:
    iOS: 13.4

schemes:
  SamplePlaybook:
    build:
      targets:
        SamplePlaybook: all
    test:
      targets:
        - SampleSnapshot
      commandLineArguments:
        -AppleLanguages (en): true
      environmentVariables:
        SNAPSHOT_DIR: $(SOURCE_ROOT)/../Snapshots/Example

targets:
  SamplePlaybook:
    Example:
    type: application
    platform: iOS
    sources: SamplePlaybook
    dependencies:
      - target: SampleComponent
      - target: Playbook/Playbook
      - target: Playbook/PlaybookUI
    configFiles:
      Debug: ../XCConfigs/project.xcconfig
      Release: ../XCConfigs/project.xcconfig

  SampleSnapshot:
    type: bundle.unit-test
    platform: iOS
    sources:
      - SampleSnapshot
    dependencies:
      - target: SamplePlaybook
      - target: Playbook/PlaybookSnapshot
    configFiles:
      Debug: ../XCConfigs/project.xcconfig
      Release: ../XCConfigs/project.xcconfig

  SampleApp:
    type: application
    platform: iOS
    sources:
      - SampleApp
    dependencies:
      - target: SampleComponent
    configFiles:
      Debug: ../XCConfigs/project.xcconfig
      Release: ../XCConfigs/project.xcconfig

  SampleComponent:
    type: framework
    platform: iOS
    sources:
      - SampleComponent
    configFiles:
      Debug: ../XCConfigs/project.xcconfig
      Release: ../XCConfigs/project.xcconfig
