name: GitHub Actions
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  macOS:
    name: Test on macOS
    runs-on: macOS-10.15
    strategy:
      matrix:
        xcode_version:
          - "11.3.1"
          - "11.4.1"
          - "12.2"
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - uses: actions/checkout@v2
      - name: Show environments
        run: |
          swift --version
          xcodebuild -version
          git branch
          git shortlog

      - name: Get ruby gem cache
        id: gem-cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-1-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-1-gem-

      - name: Install ruby gems
        if: steps.gem-cache.cache.outputs.cache-hit != 'true'
        run: make gem

      - name: Get SwiftPM cache
        uses: actions/cache@v2
        with:
          path: Tools/.build
          key: ${{ runner.os }}-${{ matrix.xcode_version }}-0-spm-${{ hashFiles('Tools/Package.resolved') }}
          restore-keys: ${{ runner.os }}-${{ matrix.xcode_version }}-0-spm-

      - name: Validation
        if: matrix.xcode_version == '12.2'
        run: make all && [ -z "$(git status --porcelain)" ] && make lint

      - name: Podspec lint
        run: make pod-lib-lint

      - name: Test library iOS
        run: set -o pipefail && xcodebuild build-for-testing test-without-building -project Playbook.xcodeproj -scheme Playbook -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro' ENABLE_TESTABILITY=YES | xcpretty -c
